/**
 * List of people named in the Epstein files.
 * Each entry has:
 *   - name:   display name to search for in page text
 *   - anchor: fragment identifier on the Wikipedia article
 *
 * Wikipedia article:
 * https://en.wikipedia.org/wiki/List_of_people_named_in_the_Epstein_files
 */
const EPSTEIN_LIST = [
  { name: "Anil Ambani",          anchor: "Anil_Ambani" },
  { name: "Eva Andersson-Dubin",  anchor: "Eva_Andersson-Dubin" },
  { name: "Dan Ariely",           anchor: "Dan_Ariely" },
  { name: "Peter Attia",          anchor: "Peter_Attia" },
  { name: "José María Aznar",     anchor: "Jos%C3%A9_Mar%C3%ADa_Aznar" },
  { name: "Joscha Bach",          anchor: "Joscha_Bach" },
  { name: "Doug Band",            anchor: "Doug_Band" },
  { name: "Steve Bannon",         anchor: "Steve_Bannon" },
  { name: "Ehud Barak",           anchor: "Ehud_Barak" },
  { name: "Tom Barrack",          anchor: "Tom_Barrack" },
  { name: "Sergei Belyakov",      anchor: "Sergei_Belyakov" },
  { name: "Leon Black",           anchor: "Leon_Black" },
  { name: "David Blaine",         anchor: "David_Blaine" },
  { name: "Todd Boehly",          anchor: "Todd_Boehly" },
  { name: "Leon Botstein",        anchor: "Leon_Botstein" },
  { name: "Ana Botella",          anchor: "Ana_Botella" },
  { name: "Edward Boyden",        anchor: "Edward_Boyden" },
  { name: "Richard Branson",      anchor: "Richard_Branson" },
  { name: "Børge Brende",         anchor: "B%C3%B8rge_Brende" },
  { name: "Flavio Briatore",      anchor: "Flavio_Briatore" },
  { name: "Sergey Brin",          anchor: "Sergey_Brin" },
  { name: "John Brockman",        anchor: "John_Brockman" },
  { name: "David Brooks",         anchor: "David_Brooks" },
  { name: "Jean-Luc Brunel",      anchor: "Jean-Luc_Brunel" },
  { name: "William Burns",        anchor: "William_Burns" },
  { name: "Naomi Campbell",       anchor: "Naomi_Campbell" },
  { name: "Frédéric Chaslin",     anchor: "Fr%C3%A9d%C3%A9ric_Chaslin" },
  { name: "Noam Chomsky",         anchor: "Noam_Chomsky" },
  { name: "Deepak Chopra",        anchor: "Deepak_Chopra" },
  { name: "George Church",        anchor: "George_Church" },
  { name: "Vitaly Churkin",       anchor: "Vitaly_Churkin" },
  { name: "Bill Clinton",         anchor: "Bill_Clinton" },
  { name: "David Copperfield",    anchor: "David_Copperfield" },
  { name: "Bill Cosby",           anchor: "Bill_Cosby" },
  { name: "Richard Dawkins",      anchor: "Richard_Dawkins" },
  { name: "Alan Dershowitz",      anchor: "Alan_Dershowitz" },
  { name: "Maria Drokova",        anchor: "Maria_Drokova" },
  { name: "Glenn Dubin",          anchor: "Glenn_Dubin" },
  { name: "Andrew Farkas",        anchor: "Andrew_Farkas" },
  { name: "Sarah Ferguson",       anchor: "Sarah_Ferguson" },
  { name: "Bill Gates",           anchor: "Bill_Gates" },
  { name: "David Gelernter",      anchor: "David_Gelernter" },
  { name: "Virginia Giuffre",     anchor: "Virginia_Giuffre" },
  { name: "Seth Glickenhaus",     anchor: "Seth_Glickenhaus" },
  { name: "Boris Johnson",        anchor: "Boris_Johnson" },
  { name: "Stephen Hawking",      anchor: "Stephen_Hawking" },
  { name: "Dustin Hoffman",       anchor: "Dustin_Hoffman" },
  { name: "Reid Hoffman",         anchor: "Reid_Hoffman" },
  { name: "Terje Rød-Larsen",     anchor: "Terje_R%C3%B8d-Larsen" },
  { name: "Ghislaine Maxwell",    anchor: "Ghislaine_Maxwell" },
  { name: "George Mitchell",      anchor: "George_Mitchell" },
  { name: "Edmond de Rothschild", anchor: "Edmond_de_Rothschild" },
  { name: "Cathy Alexander",      anchor: "Cathy_Alexander" },
  { name: "Al Gore",              anchor: "Al_Gore" },
  { name: "Gwendolyn Beck",       anchor: "Gwendolyn_Beck" },
  { name: "Leonardo DiCaprio",    anchor: "Leonardo_DiCaprio" },
  { name: "Cameron Diaz",         anchor: "Cameron_Diaz" },
  { name: "Kevin Spacey",         anchor: "Kevin_Spacey" },
  { name: "Chris Tucker",         anchor: "Chris_Tucker" },
  { name: "Donald Trump",         anchor: "Donald_Trump" },
  { name: "Prince Andrew",        anchor: "Prince_Andrew" },
  { name: "Thomas Pritzker",      anchor: "Thomas_Pritzker" },
  { name: "Leslie Wexner",        anchor: "Leslie_Wexner" },
  { name: "Mortimer Zuckerman",   anchor: "Mortimer_Zuckerman" }
];
